### ISSUE TITLE
Error with extents

### ISSUE THREAD

**Issue by thk686** [environmentalinformatics-marburg/gimms#2]
Sorry I don't have a reproducible example (can work on that at some point) but wanted to note that when I use an 'sf' object to set extents in 'rasterizeGimms' I get

> Error in checkForRemoteErrors(val) : 
>   one node produced an error: extents do not overlap

This also happens if I convert the object to a 'Spatial' type. These types should work fine with the 'raster' package. Not sure where it is going wrong.

**Comment by thk686** [comment]
Was a projection issue. Perhaps add a check for crs 4326?

**Comment by fdetsch** [comment]
Might prove valuable, thanks for the suggestion!
