### ISSUE TITLE
handle_setopt error

### ISSUE THREAD

**Issue by WangChunhu** [environmentalinformatics-marburg/gimms#9]
# Hi, author
# This is an official example, and my system is windows，R version is 4.3.1 and gimms is 1.2.1
### 'Date' method
tmp <- tempdir()
gimms_files_date <- downloadGimms(x = as.Date("2000-01-01"), y = as.Date("2000-12-31"), dsn = tmp)

### It will report an error
Error in handle_setopt(h, ...) : 
&nbsp;&nbsp; Value for option userpwd (10005) must be length-1 string

**Comment by fdetsch** [comment]
Thanks for bringing this to my attention. Can you try again with what's currently on branch `9-handle_setopt-error`?

```r
## install pkg devel version
remotes::install_github(
  "environmentalinformatics-marburg/gimms"
  , ref = "9-handle_setopt-error"
)
```

**Comment by WangChunhu** [comment]
### Hi,  Florian
#### Thank you very much, your solution has worked.

**Comment by fdetsch** [comment]
Awesome, thanks for testing. I'll try to bring the necessary changes to CRAN as soon as possible.

**Comment by WangChunhu** [comment]
Hi Florian,


May I ask if there is a specific date for NDVI data that is available twice a month？


Best regards


Chunhu Wang
2023.8.10

--------------原始邮件--------------
发件人："Florian&nbsp;Detsch ***@***.***&gt;;
发送时间：2023年8月10日(星期四) 凌晨2:37
收件人："environmentalinformatics-marburg/gimms" ***@***.***&gt;;
抄送："王春虎 ***@***.***&gt;;"Author ***@***.***&gt;;
主题：Re: [environmentalinformatics-marburg/gimms] handle_setopt error (Issue #9)
-----------------------------------

 

 
Closed #9 as completed via #10.

**Comment by fdetsch** [comment]
There's usually two values per pixel and month &ndash; one from the 1st, the other from the 15th. Does this answer your question?

**Comment by WangChunhu** [comment]
Year,&nbsp; we need the two specific dates of each month, such as January 5th, May 16th, because we want to use them to adjust the parameters in the model. Or if the dates is&nbsp;randomized?
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Thu, Aug 10, 2023 12:21 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [environmentalinformatics-marburg/gimms] handle_setopt error (Issue #9)

&nbsp;



 
There's usually two values per pixel and month – one from the 1st, the other from the 15th. Does this answer your question?

**Comment by fdetsch** [comment]
I am not sure whether this specific piece of information is available &ndash; definitely not through this package. Please let me know if you find something out. It would definitely be worth considering!

**Comment by WangChunhu** [comment]
Is there any other way to obtain the data I want？
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Thu, Aug 10, 2023 02:50 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [environmentalinformatics-marburg/gimms] handle_setopt error (Issue #9)

&nbsp;



 
I am not sure whether this specific piece of information is available – definitely not through this package. Please let me know if you find something out. It would definitely be worth considering!

**Comment by WangChunhu** [comment]
I got your meaning, thank you for your help.
